### ISSUE TITLE
Private Tab share same cookies as a normal tab

### ISSUE THREAD

**Issue by charlesmilette** [Infocatcher/Private_Tab#206]
Title says it alls. On latest Firefox Nightly with Private Tabs v 0.1.9.1pre and e10s enabled.

[Video](http://fr.tinypic.com/r/kaqmc/9)

Other little notes I gathered when using the addon:

- The private tab marker (Little white mask on violet background near the X) is still visible when I switch to the normal tab.
- I can see the new private tab button in a private browsing session.
- When I came back to the window I was for filling the issue, I had to relogin.
- The tooltip I see when overing the Windows Explorer function isn't localised:
![sans titre](https://cloud.githubusercontent.com/assets/6440374/12696690/eeabc742-c73e-11e5-9894-94ef8163127f.png)

**Comment by Infocatcher** [comment]
Tab wasn't actually private, that was fixed, see: #202.
Bug about indication should be already fixed too.

About localization. French locale isn't complete unfortunately, see
https://github.com/Infocatcher/Private_Tab/blob/master/locale/fr/pt.properties (permanent link to latest version)
https://github.com/Infocatcher/Private_Tab/blob/e4442e051e8e912c60706d8d0375adecf54e1901/locale/fr/pt.properties (current version)

Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.9.1pre3-fx-sm.xpi">private_tab-0.1.9.1pre3-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/e4442e051e8e912c60706d8d0375adecf54e1901">source code</a>).

(Anyway, looks like multi-process things was updated in latest Nightly and at least inheritance mechanism is broken again)

**Comment by charlesmilette** [comment]
FIrefox Nightly breaks a lot of things.  
One day, Stylish stopped working (noooooooo). Two weeks later: magic, it restarted working, without intervention from the maker...  
I think we should wait 'til developper edition gets updated and update the addon for it, because Firefox Nightly's APIs can change one day, and revert back the other day. It's not enough stable.

**Comment by charlesmilette** [comment]
With 0.1.9.1pre3, the private tab is really private, but I still get the indicator visible until I open a new normal tab. The "(Private Browsing)" in the title remains, even if I open a new tab.

**Comment by Infocatcher** [comment]
Now should be fixed in Firefox 45-46. And for 47+: #208.

**Comment by charlesmilette** [comment]
Fixed
