### ISSUE TITLE
Tabs lost starting with Firefox nightly April 21 build, if e10s disabled, due to bug 1345090

### ISSUE THREAD

**Issue by C4rb0n** [Infocatcher/Private_Tab#262]
If Private Tab extension is enabled on a Firefox nightly build that contains bug 1345090 (landed on April 21), and e10s is also disabled on the browser, sessionrestore loses tabs.  The only remedy is to either disable Private Tab or enable e10s.

A fix would be appreciated.  Thanks.

**Comment by Infocatcher** [comment]
May be something was already corrected in latest Nightly... Looks like all fine at least after restarts.
Can you provide some steps to reproduce this bug?

**Comment by C4rb0n** [comment]
Bug definitely still exists.  Did you make sure to disable multi-process before testing?
Here are steps:
1. Grab the latest Firefox nightly build (I'm using the 64-bit Windows build).
2. Launch Firefox and go to: Options --> General.
3. Under "Startup," for When Nightly starts, choose "Show your windows and tabs from last time"
4. Again, under "Startup," uncheck "Enable multi-process Nightly" and restart the browser
5. Install Private Tab extension
6. Browse and open up about 30 tabs to various websites on the Internet.
7. Restart Firefox.
You should find that most of your tabs permanently show up as "about:blank"

**Comment by jedie** [comment]
confirm this bug with firefox ESR v52.1.1

disable/enable fix it temporary

**Comment by B00ze64** [comment]
This was also reported on TabGroups GitHub; @C4rb0n Are you also using TabGroups?

**Comment by C4rb0n** [comment]
Nope.  Don't use TabGroups.

**Comment by B00ze64** [comment]
@jedie Are you sure this bug affects ESR 52.1.1? I'm about to update to 52 from 45 and worried, so I went ahead and read the whole bug 1345090 and it clearly states this is not uplifted to 52, and landed in FF55 only. For safety I added this to my user.js: user_pref("browser.sessionstore.restore_tabs_lazily", false);
